### ISSUE TITLE
cant opem emsf

### ISSUE THREAD

**Issue by nguny123** [efxtv/EMSF#1]
emsf
bash: /data/data/com.termux/files/usr/bin/emsf: No such file or directory

**Comment by efxtv** [comment]
Try to update with the latest version or ask on t.me/efxtv

**Comment by Zakir786Hussain70** [comment]
Error installing emsf tool.

**Comment by Zakir786Hussain70** [comment]
emsf bash: /data/data/com.termux/files/usr/bin/emsf: Bad address
