### ISSUE TITLE
bash error

### ISSUE THREAD

**Issue by Samarweb** [efxtv/EMSF#2]
bash: /data/data/com.termux/files/usr/bin/emsf: Bad address

**Comment by efxtv** [comment]
Type 
uname -a
and share the screen shot.

**Comment by Samarweb** [comment]
I am this problem again

**Comment by Samarweb** [comment]
Having*

**Comment by Samarweb** [comment]
This

**Comment by Samarweb** [comment]
Linux localhost 3.10.49-gdcb3ded #1 SMP PREEMPT Tue May 29 09:33:38 CST 2018 armv7l Android

**Comment by Samarweb** [comment]
bash: /data/data/com.termux/files/usr/bin/emsf: cannot execute binary file: Exec format error

**Comment by efxtv** [comment]
Only aarch64 is supported. If you need us to compile emsf for your device please join https://t.me/efxtv Will be a great contribution.

**Comment by Zakir786Hussain70** [comment]
bash: /data/data/com.termux/files/usr/bin/emsf: Bad address

**Comment by efxtv** [comment]
Share termux Screen shot after command :
uname -a
