### ISSUE TITLE
Ummm... The issue seems to be that this is packed full of malware??? 

### ISSUE THREAD

**Issue by jamesmac10** [efxtv/EMSF#4]
How can you put out videos on youtube telling people that don't know any better to download your app and that it is essential for getting metasploit on their android device. What a lie. You are scum. Writing bullshit programs that go all through your sensitive data, spying on you, opening ports to listen, etc. Absolutely Terrible. I hope you feel like a piece of shit because this is appalling.

**Comment by efxtv** [comment]
If you have any issues, please feel free to contact t.me/efxtv (with screenshots). We are happy to help you with the concern.
